name: Docker Image CI 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Prepare Tag Repo Info
      run: |
        echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
        
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest 
            
    - name: Log in to the Container registry
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_UPLOAD }}

    - name: Push to GitHub Container Registry
      run: | 
        docker push ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest
